(async () => {
  const labels = { PASS: "✓ עבר טוב", HARD: "! דרש יותר הסבר", DEEPEN: "★ צריך להעמיק", REVISIT: "↻ לחזור לזה" };
  const select = document.querySelector("#sessions"), details = document.querySelector("#details"), sync = document.querySelector("#sync"), exportButton = document.querySelector("#export");
  let sessions = [];
  const duration = ms => `${Math.floor(ms / 60000)}:${String(Math.floor(ms / 1000) % 60).padStart(2, "0")}`;
  async function save(session) { await chrome.storage.local.set({ [`lecturer-session:${session.session_id}`]: session }); }
  async function load() { sessions = Object.entries(await chrome.storage.local.get(null)).filter(([key]) => key.startsWith("lecturer-session:")).map(([, value]) => value).sort((a, b) => b.started_at.localeCompare(a.started_at)); select.replaceChildren(); for (const [index, session] of sessions.entries()) { const option = document.createElement("option"); option.value = index; option.textContent = `${session.lesson_id} · ${new Date(session.started_at).toLocaleString("he-IL")} · ${session.sync_status === "synced" ? "מסונכרן" : session.sync_status === "failed" ? "הסנכרון נכשל" : "מקומי"}`; select.append(option); } render(); }
  function selected() { return sessions[Number(select.value)]; }
  function render() { const session = selected(); exportButton.disabled = !session; sync.disabled = !session?.ended_at; if (!session) { details.textContent = "עדיין אין מפגשים שמורים."; return; } details.className = session.sync_status === "failed" ? "error" : "muted"; details.textContent = `${session.course_id || ""} / ${session.lesson_id} · גרסה ${session.deck_version || "לא זמינה"} · ${session.ended_at ? "הסתיים" : "עדיין לא הסתיים"} · ${session.sync_status === "synced" ? `סונכרן: ${new Date(session.last_sync_at).toLocaleString("he-IL")}` : session.sync_status === "failed" ? `הסנכרון נכשל: ${session.last_sync_error}` : "עותק מקומי נשמר"}`; const tbody = document.querySelector("tbody"); tbody.replaceChildren(); for (const slide of session.slides) { const row = document.createElement("tr"), over = slide.planned_duration_minutes !== null && slide.actual_active_duration_ms > slide.planned_duration_minutes * 60000; if (over) row.className = "signal"; [slide.slide_number, slide.planned_duration_minutes === null ? "לא זמין" : `${slide.planned_duration_minutes}:00`, duration(slide.actual_active_duration_ms), slide.annotations.map(annotation => labels[annotation.type]).join("\n") || "—", slide.annotations.map(annotation => new Date(annotation.timestamp).toLocaleString("he-IL")).join("\n") || "—"].forEach((value, index) => { const cell = document.createElement("td"); cell.textContent = value; if (index === 3 && slide.annotations.some(annotation => annotation.type !== "PASS")) cell.className = "mark"; row.append(cell); }); tbody.append(row); } }
  async function syncSession() { const session = selected(); if (!session?.ended_at) return; session.sync_status = "syncing"; await save(session); render(); try { const { lecturerSyncToken } = await chrome.storage.local.get("lecturerSyncToken"); if (!lecturerSyncToken) throw new Error("חסר אסימון סנכרון. יש להנפיק אסימון בהגדרות."); const response = await fetch(`${globalThis.SYLLO_API_BASE_URL}/api/lecturer/sessions`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${lecturerSyncToken}` }, body: JSON.stringify(session) }); if (!response.ok) throw new Error(response.status === 401 ? "האסימון אינו תקף או פג." : "Syllo לא קיבל את המפגש."); session.sync_status = "synced"; session.last_sync_at = new Date().toISOString(); session.last_sync_error = null; } catch (error) { session.sync_status = "failed"; session.last_sync_error = error instanceof Error ? error.message : "שגיאת סנכרון"; } await save(session); await load(); }
  document.querySelector("#token").addEventListener("click", async () => { const username = prompt("שם משתמש של אזור המרצה"); const password = username === null ? null : prompt("סיסמת אזור המרצה"); if (!username || password === null) return; const target = document.querySelector("#token-status"); target.className = "muted"; target.textContent = "מנפיק אסימון…"; try { const response = await fetch(`${globalThis.SYLLO_API_BASE_URL}/api/lecturer/sync-token`, { method: "POST", headers: { Authorization: `Basic ${btoa(`${username}:${password}`)}` } }); const body = await response.json(); if (!response.ok || !body.token) throw new Error(response.status === 503 ? "שירות הסנכרון אינו מוגדר ב־Syllo כרגע." : "פרטי הגישה לא התקבלו או שההגדרה חסרה."); await chrome.storage.local.set({ lecturerSyncToken: body.token }); target.className = "muted"; target.textContent = "האסימון נשמר מקומית ותקף ל־8 שעות."; } catch (error) { target.className = "error"; target.textContent = error instanceof TypeError ? "לא ניתן להתחבר ל־Syllo. בדקו חיבור אינטרנט ונסו שוב." : error instanceof Error ? error.message : "הנפקת האסימון נכשלה."; } });
  select.addEventListener("change", render); sync.addEventListener("click", syncSession); exportButton.addEventListener("click", () => { const session = selected(); if (!session) return; const url = URL.createObjectURL(new Blob([JSON.stringify(session, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `lecturer-session-${session.session_id}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); });
  try { await load(); } catch { details.textContent = "לא ניתן לקרוא את המפגשים המקומיים."; }
})();
