"use client";

import { useMemo, useState } from "react";
import styles from "./lesson-05-practice.module.css";

const tabs = ["מעבדת המרה", "גלאי מעטפת", "ארכיטקטורה", "בדיקת הבנה"];
const nfmt = (n: number, digits = 1) => new Intl.NumberFormat("he-IL", { maximumFractionDigits: digits, minimumFractionDigits: digits }).format(n);
const blocks = [
  ["אנטנה", "קולטת את סכום אותות הרדיו הנמצאים בסביבה; היא אינה בוחרת לבדה את התחנה."],
  ["מגבר RF", "מגביר אותות בתחום הרדיו ומספק סינון ראשוני. מסנן הכניסה עשוי לדחות חלק מתדרי הבבואה."],
  ["ערבל", "רכיב לא ליניארי היוצר רכיבי סכום והפרש מתוך אות RF והאות מהמתנד המקומי."],
  ["מתנד מקומי LO", "מייצר תדר שמשתנה יחד עם התחנה. בדוגמה שלנו הוא מעל RF כך שההפרש נשאר IF."],
  ["מגבר IF", "מסנן ומגביר סביב תדר ביניים קבוע. הוא מאפשר להשתמש במסנן קבוע שתוכנן לסלקטיביות הנדרשת."],
  ["גלאי מעטפת", "דיודה וקבוע זמן RC מחלצים את השינויים האיטיים במעטפת כאות שמע."],
  ["AGC", "מודד את רמת האות ומחזיר בקרה לדרגות ההגברה כדי לצמצם הבדלי עוצמה בין תחנות."]
];

function TunerLab() {
  const [rf, setRf] = useState(1000); const [interference, setInterference] = useState(1910); const iff = 455; const lo = rf + iff; const image = rf + 2 * iff; const isImage = Math.abs(interference - image) <= 1;
  const min = 400, max = 2600, pos = (v: number) => 4 + (v - min) / (max - min) * 92;
  return <div className={styles.grid}>
    <section className={styles.card}><h2>שנו את התחנה ובדקו את תדר הבבואה</h2><Control label="תדר התחנה הנקלטת · RF" value={`${rf} kHz`} min={540} max={1600} step={1} current={rf} set={setRf}/><Control label="תדר תחנה זרה" value={`${interference} kHz`} min={540} max={2500} step={1} current={interference} set={setInterference}/><p className={styles.formula}>LO = RF + IF · IM = RF + 2IF · IF = 455 kHz</p><div className={styles.metrics}><Metric label="תדר תחנה RF" value={`${rf} kHz`}/><Metric label="מתנד מקומי LO" value={`${lo} kHz`}/><Metric label="תדר ביניים IF" value="455 kHz"/><Metric label="תדר בבואה IM" value={`${image} kHz`}/></div><p className={`${styles.alert} ${isImage ? styles.warn : styles.ok}`} role="status">{isImage ? `התחנה הזרה (${interference} kHz) תואמת לתדר הבבואה ועלולה לעבור לאותו IF.` : `התחנה הזרה (${interference} kHz) אינה בתדר הבבואה הנוכחי (${image} kHz).`}</p></section>
    <section className={styles.card}><h2>ציר תדרים · לפני הערבל</h2><p>המרחק בין RF ל־LO שווה IF. תדר הבבואה נמצא באותו מרחק מעבר ל־LO.</p><div className={styles.axis}><div className={styles.axisLine}/>{[[rf,"RF",styles.blue],[lo,"LO",styles.orange],[image,"IM",styles.purple],[interference,"תחנה זרה",isImage?styles.red:styles.gray]].map(([value,label,color])=><div key={String(label)} className={`${styles.marker} ${color}`} style={{ left: `${pos(Number(value))}%` }}><i/><b>{label}</b><small dir="ltr">{value} kHz</small></div>)}</div><p className={styles.caption}>תצוגה סכמטית של תדרי הטון. ערבל אידאלי יוצר רכיבי סכום והפרש; מסנן ה־IF מעביר את ההפרש המתאים.</p><div className={styles.notice}>בדיקה: אם <bdi dir="ltr">|f<sub>interference</sub> − f<sub>IM</sub>| ≤ 1 kHz</bdi>, המעבדה מסמנת התאמה. במקלט אמיתי, רוחב הפס והסינון קובעים את ההשפעה בפועל.</div></section>
  </div>;
}

function Control({ label, value, min, max, step, current, set }: { label: string; value: string; min: number; max: number; step: number; current: number; set: (n: number) => void }) {
  return <label className={styles.control}><span>{label}<output dir="ltr">{value}</output></span><input type="range" min={min} max={max} step={step} value={current} onChange={(e) => set(Number(e.target.value))}/></label>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className={styles.metric}><small>{label}</small><b dir="ltr">{value}</b></div>; }

function DetectorLab() {
  const [fm,setFm]=useState(5); const [ma,setMa]=useState(.8); const [r,setR]=useState(10); const [c,setC]=useState(1.5);
  const fc=455; const tau=r*c; const low=1e3/fc; const high=1e3/(2*fm*Math.log((1+ma)/(1-ma))); const valid=tau>low*1.5&&tau<high*.8;
  const paths=useMemo(()=>{const count=18000, duration=.002, dt=duration/count, cap=0, values:number[]=[];let voltage=0;for(let i=0;i<count;i++){const t=i*dt;const env=1+ma*Math.cos(2*Math.PI*fm*1000*t);const input=env*Math.sin(2*Math.PI*fc*1000*t);if(input>voltage)voltage=input;else voltage*=Math.exp(-dt/(tau*1e-6));if(i%18===0)values.push(voltage);}const maxAmp=1+ma;const points=values.map((v,i)=>`${(i/(values.length-1)*640).toFixed(1)},${(120-v/maxAmp*92).toFixed(1)}`).join(" ");const envelope=values.map((_,i)=>{const t=i/(values.length-1)*duration;return `${(i/(values.length-1)*640).toFixed(1)},${(120-(1+ma*Math.cos(2*Math.PI*fm*1000*t))/maxAmp*92).toFixed(1)}`}).join(" ");return{points,envelope};},[fc,fm,ma,tau]);
  return <div className={styles.grid}><section className={styles.card}><h2>מעבדת קבוע זמן RC</h2><p>כוונו את תדר המידע, עומק האפנון ורכיבי הגלאי. הגרף מדמה דיודה אידאלית וקבל שנפרק דרך נגד.</p><Control label="תדר מידע מרבי · fm" value={`${nfmt(fm)} kHz`} min={1} max={10} step={.5} current={fm} set={setFm}/><Control label="מקדם אפנון · ma" value={ma.toFixed(2)} min={.1} max={.95} step={.05} current={ma} set={setMa}/><Control label="נגד פריקה · R" value={`${nfmt(r)} kΩ`} min={1} max={50} step={1} current={r} set={setR}/><Control label="קבל סינון · C" value={`${nfmt(c)} nF`} min={.1} max={10} step={.1} current={c} set={setC}/><div className={styles.metrics}><Metric label="קבוע זמן RC" value={`${nfmt(tau)} μs`}/><Metric label="גבול תחתון 1/fc" value={`${nfmt(low,2)} μs`}/><Metric label="גבול עליון לפי המודל" value={`${nfmt(high)} μs`}/></div><p className={`${styles.alert} ${valid?styles.ok:styles.warn}`} role="status">{valid?"בחירה סבירה בתוך תחום התכנון בקירוב.":tau<=low*1.5?"RC קטן מדי: אדוות בתדר הנושא עלולות להישאר במוצא.":"RC גדול מדי: הפריקה עלולה לא לעקוב אחרי הירידה במעטפת וליצור עיוות אלכסוני."}</p><p className={styles.caption}>הגבולות מסומנים כ־≪ ו־≪, ולכן אין נקודת חיתוך חדה. המעבדה משתמשת במרווחי הנדסה בקירוב (1.5× מהגבול התחתון ועד 0.8× מהעליון).</p></section><section className={styles.card}><h2>אות הכניסה ומוצא הגלאי</h2><svg className={styles.plot} viewBox="0 0 640 160" role="img" aria-label="סימולציה סכמטית של מעטפת AM ומתח הקבל בגלאי"><line x1="0" x2="640" y1="120" y2="120"/><polyline points={paths.envelope} className={styles.envLine}/><polyline points={paths.points} className={styles.detectorLine}/><text x="10" y="16">מעטפת אידאלית</text><text x="630" y="16" textAnchor="end">מתח קבל</text></svg><p>המעטפת העליונה היא יעד הגילוי. מתח הקבל נטען בשיאים החיוביים ונפרק בין השיאים דרך <bdi dir="ltr">R</bdi>.</p><div className={styles.notice}>מודל לימודי: דיודה אידאלית, ללא התנגדות מקור, נפילת דיודה, רעש או עומס נוסף. תוצאת המעבדה אינה סימולציית מעגל SPICE.</div></section></div>;
}

function Architecture() { const [selected,setSelected]=useState(0);return <section className={styles.card}><h2>מגלים את תפקיד כל בלוק</h2><p>בחרו דרגה בתרשים, ואז קראו מה היא עושה לאורך מסלול האות.</p><div className={styles.blocks}>{blocks.map(([name],i)=><button key={name} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{name}</button>)}</div><article className={styles.blockDetail}><span>שלב {selected+1} מתוך {blocks.length}</span><h3>{blocks[selected][0]}</h3><p>{blocks[selected][1]}</p></article><div className={styles.flow}>{blocks.map(([name],i)=><span key={name}>{name}{i<blocks.length-1&&<b>→</b>}</span>)}</div></section>; }

function Quiz() { const [answers,setAnswers]=useState<Record<string,string>>({}); const [checked,setChecked]=useState<Record<string,boolean>>({}); const items=[{id:"lo",q:"מקלט מכוון ל־RF=800 kHz, וה־IF הוא 455 kHz. מצאו LO בהזרקה גבוהה.",answer:1255,unit:"kHz",hint:"LO = RF + IF"},{id:"image",q:"מהו תדר הבבואה לאותו מקלט?",answer:1710,unit:"kHz",hint:"IM = RF + 2IF"},{id:"tau",q:"בגלאי עם R=10 kΩ ו־C=1.5 nF, מהו RC?",answer:15,unit:"μs",hint:"kΩ × nF נותן μs"}]; return <section className={styles.card}><h2>בדיקת הבנה עצמית</h2><p>נסו לענות לפני בדיקת כל סעיף. תקבלו רמז כשיש טעות; הפתרון המלא מופיע לאחר תשובה נכונה.</p>{items.map(item=>{const value=Number(answers[item.id]);const correct=checked[item.id]&&Math.abs(value-item.answer)<.01;return <article className={styles.question} key={item.id}><h3>{item.q}</h3><label>תשובה <span className={styles.ltr}>{item.unit}</span><input type="number" value={answers[item.id]??""} onChange={e=>{setAnswers(a=>({...a,[item.id]:e.target.value}));setChecked(c=>({...c,[item.id]:false}))}}/></label><button onClick={()=>setChecked(c=>({...c,[item.id]:true}))}>בדיקה</button>{checked[item.id]&&<p className={correct?styles.ok:styles.warn} role="status">{correct?`נכון: ${item.answer} ${item.unit}. ${item.hint}.`:`בדקו שוב. רמז: ${item.hint}.`}</p>}</article>})}</section>; }

export default function Lesson05Practice() { const [active,setActive]=useState(0);return <main className={styles.app} dir="rtl"><header className={styles.mast}><div><div className={styles.eyebrow}>מערכות תקשורת · שיעור 5 · תרגול אינטראקטיבי</div><h1>מעבדת מקלט AM סופר־הטרודיין</h1></div><p>מסלול התרגול: מכוונים תחנה, בוחנים תדר בבואה, מתכננים RC, מזהים את דרגות המקלט ופוערים את ההבנה.</p></header><nav className={styles.tabs} role="tablist" aria-label="חלקי התרגול">{tabs.map((tab,i)=><button key={tab} role="tab" aria-selected={active===i} aria-controls="lesson5-panel" id={`lesson5-tab-${i}`} onKeyDown={(event)=>{if(event.key==="ArrowLeft"||event.key==="ArrowRight"){event.preventDefault();const next=(i+(event.key==="ArrowLeft"?-1:1)+tabs.length)%tabs.length;setActive(next);document.getElementById("lesson5-tab-"+next)?.focus();}}} onClick={()=>setActive(i)}>{i+1} · {tab}</button>)}</nav><section id="lesson5-panel" role="tabpanel" aria-labelledby={`lesson5-tab-${active}`}>{active===0?<TunerLab/>:active===1?<DetectorLab/>:active===2?<Architecture/>:<Quiz/>}</section><footer>התרגול פועל מקומית בדפדפן. המעבדות הן מודלים לימודיים ואינן מודדות מקלט פיזי.</footer></main>; }
